--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ExodusDevs/Scoreboard
build-by-default: true
branches:
- stable
projects:
  Scoreboard:
    path: ""
    model: virion
    type: library
...
